### PR TITLE
Proxy protocol v2 support, IPv6 support

### LINKED ISSUE #23: Proxy protocol version 2
Hi there, I'm currently using your module to test [PRX](https://github.com/manvalls/prx), I'd like to know if the PROXY protocol version 2 is on the roadmap since it represents around 20% of PRX's code. I don't want to implement it myself as I want PRX's PROXY protocol implementation to be validated by a 3rd party.

### LINKED ISSUE #28: proxy protcol v1 or v2
This project support both versions or one of them. Please add more detail information about compatible version of proxy protocol. Thank you guys

### PR DESCRIPTION
**Pull request by gugu**
1. Fixes #23 and fixes #28 for proxy protocol v2
2. Uses proxy-protocol-v2 module instead of regex
3. Removed dependency on `findhit-util` by using native node functions
4. Remove the support of node.js < 10

### CODE REVIEW

**Comment by gugu** [comment]
@cusspvz can you please review this PR?

**Comment by gugu** [comment]
I think there is too many changes for PR, I'll do a fork

**Comment by cusspvz** [comment]
Hey @gugu,

first of all, thank you so much for contributing to this project. Right now I've still a lot of stuff on my plate, so I have this PR open on my computer for a while. I'm really interested in merging your contribution but I have to review and test it. I'm going to reopen this, but in case you need this upfront, I'd advise you to create your own fork and use it directly until we get this merged.

Thank you, looking forward to merging this and sorry for letting you in the dark!

**Comment by gugu** [comment]
Let's keep this in draft state (now it has a major rewrite to support http2 and bugfix when socket.setTimeout() did not work on proxied server)

**Pull request closed without merging**
